variables:
- group: uipath-cicd

jobs:
- job:
  displayName: Build the docker image
  timeoutInMinutes: 360

  pool:
    vmImage: windows-latest

  steps:
    - task: AzureCLI@2
      displayName: Build and Push the Docker image
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: | 
          docker build -t $(containerRegistry).azurecr.io/$(repositoryName) .
          az acr login --name $(containerRegistry)
          docker push $(containerRegistry).azurecr.io/$(repositoryName):latest
